import { FinancialTransaction, FinancialStats, InventoryItem, InventoryStats, MinibarItem, RoomMinibarConsumption, StockMovement, StockMovementType } from '../types.ts';
import { getSupabaseClient } from './supabase.ts';
const client=()=>{const s=getSupabaseClient();if(!s)throw new Error('Supabase não configurado.');return s;};
const num=(v:any)=>Number(v||0);
const mapMinibar=(r:any):MinibarItem=>({id:r.id,name:r.name,category:r.category,price:num(r.price),stockQty:num(r.stock_qty),unit:r.unit||'un'} as MinibarItem);
const mapTx=(r:any):FinancialTransaction=>({id:r.id,type:r.type,category:r.category,description:r.description,amount:num(r.amount),paymentMethod:r.payment_method,status:r.status,reservationId:r.reservation_id||undefined,roomNumber:r.room_number||undefined,guestName:r.guest_name||undefined,date:r.date,createdAt:r.created_at} as FinancialTransaction);
const mapInv=(r:any):InventoryItem=>({id:r.id,sku:r.sku,name:r.name,sector:r.sector,category:r.category,currentStock:num(r.current_stock),minStock:num(r.min_stock),maxStock:r.max_stock==null?undefined:num(r.max_stock),unit:r.unit,costPrice:num(r.cost_price),sellingPrice:r.selling_price==null?undefined:num(r.selling_price),supplier:r.supplier||undefined,locationBarcode:r.location_barcode||undefined,linkedMinibarItemId:r.linked_minibar_item_id||undefined,linkedMenuItemId:r.linked_menu_item_id||undefined,updatedAt:r.updated_at} as InventoryItem);
const mapMov=(r:any):StockMovement=>({id:r.id,timestamp:r.timestamp,itemId:r.item_id||'',itemName:r.item_name,sector:r.sector,type:r.type,quantity:num(r.quantity),previousStock:num(r.previous_stock),newStock:num(r.new_stock),unitCost:num(r.unit_cost),totalCost:num(r.total_cost),originLocation:r.origin_location||undefined,destinationLocation:r.destination_location||undefined,relatedRoomNumber:r.related_room_number||undefined,relatedReservationId:r.related_reservation_id||undefined,relatedOrderId:r.related_order_id||undefined,operator:r.operator||'',documentNumber:r.document_number||undefined,notes:r.notes||undefined} as StockMovement);
const mapCons=(r:any):RoomMinibarConsumption=>({id:r.id,roomId:r.room_id||'',roomNumber:r.room_number,reservationId:r.reservation_id||'',guestName:r.guest_name||'',itemId:r.item_id||'',itemName:r.item_name,quantity:num(r.quantity),unitPrice:num(r.unit_price),totalPrice:num(r.total_price),registeredBy:r.registered_by||'',registeredAt:r.registered_at,status:r.status} as RoomMinibarConsumption);
export async function loadMinibarItemsCloud(){const{data,error}=await client().from('minibar_items').select('*').order('name');if(error)throw error;return(data||[]).map(mapMinibar);}
export async function createMinibarItemCloud(item:Omit<MinibarItem,'id'>){const row={id:`mb_${Date.now()}_${Math.floor(Math.random()*1000)}`,name:item.name,category:item.category,price:num(item.price),stock_qty:num(item.stockQty),unit:item.unit||'un'};const{data,error}=await client().from('minibar_items').insert(row).select('*').single();if(error)throw error;return mapMinibar(data);}
export async function updateMinibarItemCloud(id:string,u:Partial<MinibarItem>){const p:any={};if('name'in u)p.name=u.name;if('category'in u)p.category=u.category;if('price'in u)p.price=num(u.price);if('stockQty'in u)p.stock_qty=num(u.stockQty);if('unit'in u)p.unit=u.unit;const{data,error}=await client().from('minibar_items').update(p).eq('id',id).select('*').single();if(error)throw error;return mapMinibar(data);}
export async function restockMinibarItemCloud(id:string,q:number){const s=client();const{data:c,error:e}=await s.from('minibar_items').select('*').eq('id',id).single();if(e)throw e;return updateMinibarItemCloud(id,{stockQty:num(c.stock_qty)+num(q)});}
export async function deleteMinibarItemCloud(id:string){const{error}=await client().from('minibar_items').delete().eq('id',id);if(error)throw error;return{success:true};}
export async function loadConsumptionsCloud(roomId?:string){let q=client().from('room_consumptions').select('*').order('registered_at',{ascending:false});if(roomId)q=q.eq('room_id',roomId);const{data,error}=await q;if(error)throw error;return(data||[]).map(mapCons);}
export async function registerConsumptionCloud(input:{roomId:string;itemId:string;quantity:number;registeredBy:string}){
  const s=client();
  const qty=Math.max(1,Math.floor(num(input.quantity)));
  const {data,error}=await s.rpc('register_minibar_consumption_atomic',{
    p_room_id:input.roomId,
    p_item_id:input.itemId,
    p_quantity:qty,
    p_registered_by:input.registeredBy||'Sistema'
  });
  if(error)throw error;
  return mapCons(data);
}
export async function loadTransactionsCloud(){const{data,error}=await client().from('financial_transactions').select('*').order('date',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;return(data||[]).map(mapTx);}
export async function createTransactionCloud(tx:Omit<FinancialTransaction,'id'|'createdAt'>){const now=new Date().toISOString();const row={id:`tx_${Date.now()}_${Math.floor(Math.random()*1000)}`,type:tx.type,category:tx.category,description:tx.description,amount:num(tx.amount),payment_method:tx.paymentMethod,status:tx.status,reservation_id:tx.reservationId||null,room_number:tx.roomNumber||null,guest_name:tx.guestName||null,date:tx.date,created_at:now};const{data,error}=await client().from('financial_transactions').insert(row).select('*').single();if(error)throw error;return mapTx(data);}
export async function loadFinancialStatsCloud():Promise<FinancialStats>{const tx=await loadTransactionsCloud();const today=new Date().toISOString().slice(0,10),month=today.slice(0,7);const rev=tx.filter(x=>x.type==='Receita'),exp=tx.filter(x=>x.type==='Despesa'),sum=(a:FinancialTransaction[])=>a.reduce((s,x)=>s+x.amount,0);const totalRevenueMonth=sum(rev.filter(x=>x.date.startsWith(month))),totalExpensesMonth=sum(exp.filter(x=>x.date.startsWith(month)));const cats=new Map<string,{amount:number,count:number}>();rev.filter(x=>x.date.startsWith(month)).forEach(x=>{const c=cats.get(x.category)||{amount:0,count:0};c.amount+=x.amount;c.count++;cats.set(x.category,c)});const methods=new Map<string,number>();rev.filter(x=>x.date.startsWith(month)).forEach(x=>methods.set(x.paymentMethod,(methods.get(x.paymentMethod)||0)+x.amount));const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const date=d.toISOString().slice(0,10);return{date,label:d.toLocaleDateString('pt-BR',{weekday:'short'}),amount:sum(rev.filter(x=>x.date===date))}});return{totalRevenueMonth,totalRevenueToday:sum(rev.filter(x=>x.date===today)),totalPendingFolios:sum(rev.filter(x=>x.status==='Pendente')),totalExpensesMonth,netIncomeMonth:totalRevenueMonth-totalExpensesMonth,byCategory:[...cats].map(([category,v])=>({category,...v})),byPaymentMethod:[...methods].map(([method,amount])=>({method,amount,percentage:totalRevenueMonth?amount/totalRevenueMonth*100:0})),dailyRevenueLast7Days:days};}
export async function loadInventoryItemsCloud(sector?:string,lowStock?:boolean){let q=client().from('inventory_items').select('*').order('name');if(sector&&sector!=='ALL')q=q.eq('sector',sector);const{data,error}=await q;if(error)throw error;let rows=(data||[]).map(mapInv);if(lowStock)rows=rows.filter(x=>x.currentStock<=x.minStock);return rows;}
export async function loadInventoryItemCloud(id:string){const{data,error}=await client().from('inventory_items').select('*').eq('id',id).single();if(error)throw error;return mapInv(data);}
export async function createInventoryItemCloud(i:Omit<InventoryItem,'id'|'updatedAt'>){const now=new Date().toISOString();const row={id:`inv_${Date.now()}_${Math.floor(Math.random()*1000)}`,sku:i.sku,name:i.name,sector:i.sector,category:i.category,current_stock:num(i.currentStock),min_stock:num(i.minStock),max_stock:i.maxStock??null,unit:i.unit,cost_price:num(i.costPrice),selling_price:i.sellingPrice??null,supplier:i.supplier||null,location_barcode:i.locationBarcode||null,linked_minibar_item_id:i.linkedMinibarItemId||null,linked_menu_item_id:i.linkedMenuItemId||null,updated_at:now};const{data,error}=await client().from('inventory_items').insert(row).select('*').single();if(error)throw error;return mapInv(data);}
export async function updateInventoryItemCloud(id:string,u:Partial<InventoryItem>){const p:any={updated_at:new Date().toISOString()};const m:any={sku:'sku',name:'name',sector:'sector',category:'category',currentStock:'current_stock',minStock:'min_stock',maxStock:'max_stock',unit:'unit',costPrice:'cost_price',sellingPrice:'selling_price',supplier:'supplier',locationBarcode:'location_barcode',linkedMinibarItemId:'linked_minibar_item_id',linkedMenuItemId:'linked_menu_item_id'};for(const[k,c]of Object.entries(m))if(Object.prototype.hasOwnProperty.call(u,k))p[c]=(u as any)[k]??null;const{data,error}=await client().from('inventory_items').update(p).eq('id',id).select('*').single();if(error)throw error;return mapInv(data);}
export async function deleteInventoryItemCloud(id:string){const{error}=await client().from('inventory_items').delete().eq('id',id);if(error)throw error;return{success:true};}
export async function registerStockMovementCloud(input:{itemId:string;type:StockMovementType;quantity:number;unitCost?:number;originLocation?:string;destinationLocation?:string;relatedRoomNumber?:string;relatedReservationId?:string;operator?:string;documentNumber?:string;notes?:string}){const s=client();const{data:item,error}=await s.from('inventory_items').select('*').eq('id',input.itemId).single();if(error)throw error;const qty=Math.abs(num(input.quantity)),prev=num(item.current_stock);let next=prev;if(input.type==='Entrada_Compra')next=prev+qty;else if(input.type==='Ajuste_Inventario')next=qty;else if(input.type==='Transferencia')next=prev;else next=Math.max(0,prev-qty);const unit=input.unitCost&&input.unitCost>0?num(input.unitCost):num(item.cost_price),now=new Date().toISOString();const row={id:`mov_${Date.now()}_${Math.floor(Math.random()*1000)}`,timestamp:now,item_id:item.id,item_name:item.name,sector:item.sector,type:input.type,quantity:qty,previous_stock:prev,new_stock:next,unit_cost:unit,total_cost:unit*qty,origin_location:input.originLocation||null,destination_location:input.destinationLocation||null,related_room_number:input.relatedRoomNumber||null,related_reservation_id:input.relatedReservationId||null,operator:input.operator||'Sistema',document_number:input.documentNumber||null,notes:input.notes||null};const{data:mov,error:me}=await s.from('stock_movements').insert(row).select('*').single();if(me)throw me;const upd:any={current_stock:next,updated_at:now};if(input.type==='Entrada_Compra'&&input.unitCost&&input.unitCost>0)upd.cost_price=unit;await s.from('inventory_items').update(upd).eq('id',item.id);return{item:mapInv({...item,...upd}),movement:mapMov(mov)};}
export async function loadStockMovementsCloud(f?:{itemId?:string;sector?:string;type?:string;limit?:number}){let q=client().from('stock_movements').select('*').order('timestamp',{ascending:false});if(f?.itemId)q=q.eq('item_id',f.itemId);if(f?.sector&&f.sector!=='ALL')q=q.eq('sector',f.sector);if(f?.type&&f.type!=='ALL')q=q.eq('type',f.type);if(f?.limit)q=q.limit(f.limit);const{data,error}=await q;if(error)throw error;return(data||[]).map(mapMov);}
export async function loadInventoryStatsCloud():Promise<InventoryStats>{const[i,m]=await Promise.all([loadInventoryItemsCloud(),loadStockMovementsCloud()]);const today=new Date().toISOString().slice(0,10);const sectors=new Map<string,{count:number,valuation:number}>();i.forEach(x=>{const v=sectors.get(x.sector)||{count:0,valuation:0};v.count++;v.valuation+=x.currentStock*x.costPrice;sectors.set(x.sector,v)});return{totalItems:i.length,totalValuation:i.reduce((s,x)=>s+x.currentStock*x.costPrice,0),criticalStockCount:i.filter(x=>x.currentStock<=x.minStock).length,replenishmentSuggestedCount:i.filter(x=>x.currentStock<=x.minStock).length,movementsToday:m.filter(x=>x.timestamp.startsWith(today)).length,bySector:[...sectors].map(([sector,v])=>({sector:sector as any,...v}))};}
