import {
  HotelSettings,
  Guest,
  Room,
  Reservation,
  MinibarItem,
  MenuItem,
  KanbanTask,
  FinancialTransaction,
  InventoryItem,
  StockMovement
} from '../src/types.ts';

export const defaultSettings: HotelSettings = {
  id: 'hotel_1',
  hotelName: 'Grand Horizon Resort & Pousada',
  tagline: 'Hospitalidade Premium & Conforto Exclusivo',
  description: 'Um refúgio sofisticado com suítes de alto padrão, alta gastronomia, spa completo e experiências inesquecíveis.',
  logoIcon: 'hotel',
  primaryColor: 'emerald', // 'emerald' | 'blue' | 'amber' | 'violet' | 'rose' | 'slate'
  currency: 'R$',
  taxRatePercent: 5.0,
  checkInTime: '14:00',
  checkOutTime: '11:00',
  address: 'Av. Beira Mar, 2500 - Ponta das Pedras',
  cityState: 'Florianópolis - SC',
  phone: '+55 (48) 3344-9800',
  email: 'reservas@grandhorizon.com.br',
  bookingPolicies: 'Cancelamento gratuito até 48h antes do check-in. Café da manhã incluso em todas as diárias. Proibido fumar nos quartos.',
  wifiPassword: 'HorizonGuest2026',
  roomTypes: [
    {
      id: 'rt_standard',
      name: 'Suíte Standard',
      description: 'Aconchegante e funcional com cama queen-size, ar condicionado inverter, smart TV e varanda com vista jardim.',
      basePrice: 380,
      capacityAdults: 2,
      capacityChildren: 1,
      amenities: ['Wi-Fi 500Mbps', 'Smart TV 50"', 'Ar Condicionado', 'Frigobar', 'Cofre Digital', 'Secador de Cabelo'],
      imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80'
    },
    {
      id: 'rt_luxo',
      name: 'Suíte Luxo Vista Mar',
      description: 'Vista deslumbrante para o oceano, cama king-size, cafeteira Nespresso, enxoval 400 fios e banheira de imersão.',
      basePrice: 590,
      capacityAdults: 2,
      capacityChildren: 1,
      amenities: ['Vista Panorâmica', 'Banheira de Imersão', 'Cama King Size', 'Cafeteira Espresso', 'Roupa de Banho Egípcia', 'Wi-Fi 500Mbps'],
      imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80'
    },
    {
      id: 'rt_master',
      name: 'Suíte Presidencial com Hidro',
      description: 'Espaço generoso de 75m² com jacuzzi privativa no terraço, sala de estar integrada e atendimento VIP de mordomo.',
      basePrice: 950,
      capacityAdults: 3,
      capacityChildren: 2,
      amenities: ['Jacuzzi Privativa', 'Varanda com Deck', 'Sala de Estar', 'Menu de Travesseiros', 'Adega Climatizada', 'Café servido na suíte'],
      imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80'
    },
    {
      id: 'rt_chale',
      name: 'Chalé Família Bosque',
      description: 'Chalé reservado entre as árvores com 2 quartos, lareira ecológica e cozinha compacta equipada.',
      basePrice: 720,
      capacityAdults: 4,
      capacityChildren: 2,
      amenities: ['2 Quartos', 'Lareira', 'Mini Cozinha', 'Churrasqueira Privativa', 'Deck Panorâmico', 'Estacionamento Próprio'],
      imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80'
    }
  ]
};

export const defaultRooms: Room[] = [
  {
    id: 'room_101',
    number: '101',
    typeId: 'rt_standard',
    typeName: 'Suíte Standard',
    floor: 1,
    status: 'Ocupado',
    pricePerNight: 380,
    capacity: 2,
    currentReservationId: 'res_001',
    currentGuestName: 'Carlos Eduardo Mendes',
    amenities: ['Wi-Fi 500Mbps', 'Smart TV 50"', 'Ar Condicionado', 'Frigobar'],
    notes: 'Hóspede solicitou berço adicional.'
  },
  {
    id: 'room_102',
    number: '102',
    typeId: 'rt_standard',
    typeName: 'Suíte Standard',
    floor: 1,
    status: 'Disponivel',
    pricePerNight: 380,
    capacity: 2,
    amenities: ['Wi-Fi 500Mbps', 'Smart TV 50"', 'Ar Condicionado', 'Frigobar']
  },
  {
    id: 'room_103',
    number: '103',
    typeId: 'rt_standard',
    typeName: 'Suíte Standard',
    floor: 1,
    status: 'Limpeza',
    pricePerNight: 380,
    capacity: 2,
    amenities: ['Wi-Fi 500Mbps', 'Smart TV 50"', 'Ar Condicionado', 'Frigobar'],
    notes: 'Check-out recente. Governança acionada.'
  },
  {
    id: 'room_201',
    number: '201',
    typeId: 'rt_luxo',
    typeName: 'Suíte Luxo Vista Mar',
    floor: 2,
    status: 'Ocupado',
    pricePerNight: 590,
    capacity: 3,
    currentReservationId: 'res_002',
    currentGuestName: 'Dra. Fernanda Vasconcelos',
    amenities: ['Vista Panorâmica', 'Banheira de Imersão', 'Cama King Size', 'Cafeteira Nespresso']
  },
  {
    id: 'room_202',
    number: '202',
    typeId: 'rt_luxo',
    typeName: 'Suíte Luxo Vista Mar',
    floor: 2,
    status: 'Disponivel',
    pricePerNight: 590,
    capacity: 3,
    amenities: ['Vista Panorâmica', 'Banheira de Imersão', 'Cama King Size', 'Cafeteira Nespresso']
  },
  {
    id: 'room_203',
    number: '203',
    typeId: 'rt_luxo',
    typeName: 'Suíte Luxo Vista Mar',
    floor: 2,
    status: 'Manutencao',
    pricePerNight: 590,
    capacity: 3,
    amenities: ['Vista Panorâmica', 'Banheira de Imersão', 'Cama King Size'],
    notes: 'Ar condicionado em verificação preventiva.'
  },
  {
    id: 'room_301',
    number: '301',
    typeId: 'rt_master',
    typeName: 'Suíte Presidencial com Hidro',
    floor: 3,
    status: 'Ocupado',
    pricePerNight: 950,
    capacity: 4,
    currentReservationId: 'res_003',
    currentGuestName: 'Roberto Silveira Neto',
    amenities: ['Jacuzzi Privativa', 'Varanda com Deck', 'Sala de Estar', 'Menu de Travesseiros']
  },
  {
    id: 'room_401',
    number: '401',
    typeId: 'rt_chale',
    typeName: 'Chalé Família Bosque',
    floor: 1,
    status: 'Disponivel',
    pricePerNight: 720,
    capacity: 5,
    amenities: ['2 Quartos', 'Lareira', 'Mini Cozinha', 'Deck Panorâmico']
  }
];

export const defaultGuests: Guest[] = [
  {
    id: 'guest_001',
    fullName: 'Carlos Eduardo Mendes',
    document: '284.918.239-01',
    documentType: 'CPF',
    email: 'carlos.mendes@empresa.com.br',
    phone: '+55 (11) 98765-4321',
    address: 'Rua Bela Cintra, 1420, Apto 82',
    city: 'São Paulo',
    state: 'SP',
    birthDate: '1984-05-12',
    preferences: 'Andar baixo, cama extra firme, café sem açúcar.',
    allergiesNotes: 'Nenhuma alergia relatada.',
    status: 'VIP',
    totalStays: 4,
    totalSpent: 4850,
    createdAt: '2025-11-10T14:30:00Z',
    updatedAt: '2026-08-30T10:00:00Z'
  },
  {
    id: 'guest_002',
    fullName: 'Dra. Fernanda Vasconcelos',
    document: '193.847.502-33',
    documentType: 'CPF',
    email: 'fernanda.vasconcelos@medicina.ufrj.br',
    phone: '+55 (21) 99123-8844',
    address: 'Av. Atlântica, 3200',
    city: 'Rio de Janeiro',
    state: 'RJ',
    birthDate: '1990-09-24',
    preferences: 'Travesseiros de pluma, quarto silencioso, água com gás sempre abastecida.',
    allergiesNotes: 'Intolerância a lactose moderada.',
    status: 'VIP',
    totalStays: 6,
    totalSpent: 8900,
    createdAt: '2025-08-14T09:15:00Z',
    updatedAt: '2026-09-01T11:20:00Z'
  },
  {
    id: 'guest_003',
    fullName: 'Roberto Silveira Neto',
    document: '902.114.778-55',
    documentType: 'CPF',
    email: 'roberto.silveira@advocacia.com',
    phone: '+55 (31) 98455-1100',
    address: 'Rua dos Inconfidentes, 850',
    city: 'Belo Horizonte',
    state: 'MG',
    birthDate: '1978-02-18',
    preferences: 'Gosta de espumante gelado no check-in, jornais matutinos.',
    allergiesNotes: 'Alergia severa a frutos do mar.',
    status: 'VIP',
    totalStays: 2,
    totalSpent: 3800,
    createdAt: '2026-01-20T16:00:00Z',
    updatedAt: '2026-09-02T08:00:00Z'
  },
  {
    id: 'guest_004',
    fullName: 'Mariana Lima de Albuquerque',
    document: 'FD892019',
    documentType: 'Passaporte',
    email: 'mariana.albuquerque@gmail.com',
    phone: '+55 (41) 99988-7766',
    address: 'Alameda Dr. Carlos de Carvalho, 450',
    city: 'Curitiba',
    state: 'PR',
    birthDate: '1995-12-05',
    preferences: 'Late check-out solicitado quando possível.',
    allergiesNotes: 'Sem restrições.',
    status: 'Ativo',
    totalStays: 1,
    totalSpent: 1180,
    createdAt: '2026-08-15T18:40:00Z',
    updatedAt: '2026-08-15T18:40:00Z'
  }
];

export const defaultReservations: Reservation[] = [
  {
    id: 'res_001',
    code: 'RES-84910',
    guestId: 'guest_001',
    guestName: 'Carlos Eduardo Mendes',
    guestEmail: 'carlos.mendes@empresa.com.br',
    guestPhone: '+55 (11) 98765-4321',
    roomId: 'room_101',
    roomNumber: '101',
    roomTypeName: 'Suíte Standard',
    checkInDate: '2026-09-01',
    checkOutDate: '2026-09-05',
    nights: 4,
    adults: 2,
    children: 1,
    pricePerNight: 380,
    totalNightsAmount: 1520,
    status: 'CheckIn',
    paymentStatus: 'Parcial',
    paymentMethod: 'Cartao_Credito',
    notes: 'Entrada realizada às 14:15. Pago 50% antecipado.',
    createdAt: '2026-08-20T10:00:00Z',
    checkedInAt: '2026-09-01T14:15:00Z'
  },
  {
    id: 'res_002',
    code: 'RES-84911',
    guestId: 'guest_002',
    guestName: 'Dra. Fernanda Vasconcelos',
    guestEmail: 'fernanda.vasconcelos@medicina.ufrj.br',
    guestPhone: '+55 (21) 99123-8844',
    roomId: 'room_201',
    roomNumber: '201',
    roomTypeName: 'Suíte Luxo Vista Mar',
    checkInDate: '2026-09-02',
    checkOutDate: '2026-09-06',
    nights: 4,
    adults: 2,
    children: 0,
    pricePerNight: 590,
    totalNightsAmount: 2360,
    status: 'CheckIn',
    paymentStatus: 'Pago',
    paymentMethod: 'PIX',
    notes: 'Check-in concluído. Pagamento total via PIX aprovado.',
    createdAt: '2026-08-25T11:30:00Z',
    checkedInAt: '2026-09-02T13:50:00Z'
  },
  {
    id: 'res_003',
    code: 'RES-84912',
    guestId: 'guest_003',
    guestName: 'Roberto Silveira Neto',
    guestEmail: 'roberto.silveira@advocacia.com',
    guestPhone: '+55 (31) 98455-1100',
    roomId: 'room_301',
    roomNumber: '301',
    roomTypeName: 'Suíte Presidencial com Hidro',
    checkInDate: '2026-09-02',
    checkOutDate: '2026-09-07',
    nights: 5,
    adults: 2,
    children: 0,
    pricePerNight: 950,
    totalNightsAmount: 4750,
    status: 'CheckIn',
    paymentStatus: 'Parcial',
    paymentMethod: 'Cartao_Credito',
    notes: 'Hóspede solicitou garrafa de champagne e frutas na chegada.',
    createdAt: '2026-08-28T16:20:00Z',
    checkedInAt: '2026-09-02T15:10:00Z'
  },
  {
    id: 'res_004',
    code: 'RES-84913',
    guestId: 'guest_004',
    guestName: 'Mariana Lima de Albuquerque',
    guestEmail: 'mariana.albuquerque@gmail.com',
    guestPhone: '+55 (41) 99988-7766',
    roomId: 'room_202',
    roomNumber: '202',
    roomTypeName: 'Suíte Luxo Vista Mar',
    checkInDate: '2026-09-04',
    checkOutDate: '2026-09-07',
    nights: 3,
    adults: 2,
    children: 0,
    pricePerNight: 590,
    totalNightsAmount: 1770,
    status: 'Confirmada',
    paymentStatus: 'Pendente',
    paymentMethod: 'PIX',
    notes: 'Reserva online via site do hotel. Aguardando chegada dia 04.',
    createdAt: '2026-09-02T12:00:00Z'
  }
];

export const defaultMinibarItems: MinibarItem[] = [
  { id: 'mb_01', name: 'Água Mineral sem Gás 500ml', category: 'Bebidas', price: 8, stockQty: 120, unit: 'un' },
  { id: 'mb_02', name: 'Água Mineral com Gás 500ml', category: 'Bebidas', price: 9, stockQty: 100, unit: 'un' },
  { id: 'mb_03', name: 'Refrigerante Lata 350ml', category: 'Bebidas', price: 12, stockQty: 80, unit: 'un' },
  { id: 'mb_04', name: 'Cerveja Artesanal IPA 355ml', category: 'Bebidas', price: 24, stockQty: 60, unit: 'un' },
  { id: 'mb_05', name: 'Cerveja Long Neck Stella Artois', category: 'Bebidas', price: 18, stockQty: 75, unit: 'un' },
  { id: 'mb_06', name: 'Vinho Tinto Cabernet 375ml', category: 'Vinhos', price: 75, stockQty: 30, unit: 'un' },
  { id: 'mb_07', name: 'Espumante Brut Chandon 187ml', category: 'Vinhos', price: 65, stockQty: 25, unit: 'un' },
  { id: 'mb_08', name: 'Castanhas de Caju Nobres 80g', category: 'Snacks', price: 22, stockQty: 50, unit: 'pct' },
  { id: 'mb_09', name: 'Batata Pringles Original 40g', category: 'Snacks', price: 18, stockQty: 45, unit: 'un' },
  { id: 'mb_10', name: 'Chocolate Fino Lindt 100g', category: 'Doces', price: 28, stockQty: 40, unit: 'barra' }
];

export const defaultMenuItems: MenuItem[] = [
  { id: 'm_01', name: 'Café da Manhã Imperial na Suíte', category: 'Café da Manhã', price: 65, description: 'Cesta de pães artesanais, croissants, frutas da estação, ovos benedict, queijos nobres e café espresso.', prepTimeMinutes: 25, available: true },
  { id: 'm_02', name: 'Omelete Especial de Queijo Brie e Cogumelos', category: 'Café da Manhã', price: 42, description: 'Ovos caipiras, queijo brie derretido, shimeji salteado e torradas com azeite de ervas.', prepTimeMinutes: 15, available: true },
  { id: 'm_03', name: 'Club Sandwich do Chef', category: 'Lanches', price: 54, description: 'Três camadas de pão brioche tostado, peito de frango grelhado, bacon crocante, alface americana, tomate e maionese trufada.', prepTimeMinutes: 20, available: true },
  { id: 'm_04', name: 'Burguer Artesanal Black Angus 200g', category: 'Lanches', price: 62, description: 'Pão australiano, queijo cheddar inglês, cebola caramelizada, geleia de bacon e batatas rústicas.', prepTimeMinutes: 25, available: true },
  { id: 'm_05', name: 'Filé Mignon ao Molho Poivre com Risoto', category: 'Pratos Principais', price: 96, description: 'Medalhão de filé mignon grelhado ao molho de pimenta verde com cremoso risoto de queijo parmesão.', prepTimeMinutes: 30, available: true },
  { id: 'm_06', name: 'Salmão Grelhado com Legumes e Ervas', category: 'Pratos Principais', price: 88, description: 'Posta de salmão fresco grelhada com legumes salteados na manteiga clarified e molho de maracujá.', prepTimeMinutes: 25, available: true },
  { id: 'm_07', name: 'Fettuccine com Camarões e Raspas de Limão Siciliano', category: 'Pratos Principais', price: 92, description: 'Massa fresca grano duro, camarões grandes grelhados, tomatinhos confit e molho cremoso.', prepTimeMinutes: 25, available: true },
  { id: 'm_08', name: 'Petit Gâteau de Chocolate Belga', category: 'Sobremesas', price: 36, description: 'Bolo quente com recheio cremoso e sorvete artesanal de baunilha de Madagascar.', prepTimeMinutes: 15, available: true },
  { id: 'm_09', name: 'Suco Natural Detox Verde 400ml', category: 'Bebidas', price: 18, description: 'Couve, limão, maçã verde, gengibre e hortelã fresca.', prepTimeMinutes: 10, available: true },
  { id: 'm_10', name: 'Drink Autoral Sunset Horizon', category: 'Bebidas', price: 38, description: 'Gin Bombay, tônica artesanal, licor de flor de sabugueiro e alecrim defumado.', prepTimeMinutes: 10, available: true }
];

export const defaultTasks: KanbanTask[] = [
  // Governança / Housekeeping
  {
    id: 'task_gov_1',
    title: 'Limpeza de Checkout - Quarto 103',
    description: 'Higienização completa, troca de roupas de cama/toalhas e reposição de amenities pós-saída.',
    sector: 'Governanca',
    status: 'A_Fazer',
    priority: 'Alta',
    roomNumber: '103',
    assignedTo: 'Maria Helena (Supervisora)',
    relatedType: 'CheckOut',
    createdAt: '2026-09-02T11:05:00Z',
    updatedAt: '2026-09-02T11:05:00Z'
  },
  {
    id: 'task_gov_2',
    title: 'Arrumação e Abertura de Cama (Turn Down) - Suíte 301',
    description: 'Organizar quarto para a noite, aromatização com lavanda e bombons na cabeceira.',
    sector: 'Governanca',
    status: 'Em_Andamento',
    priority: 'Media',
    roomNumber: '301',
    guestName: 'Roberto Silveira Neto',
    assignedTo: 'Luciana Silva',
    relatedType: 'Reserva',
    createdAt: '2026-09-02T17:00:00Z',
    updatedAt: '2026-09-02T18:30:00Z'
  },
  {
    id: 'task_gov_3',
    title: 'Inspeção Pré-Chegada - Quarto 202',
    description: 'Conferência de ar-condicionado, frigobar selado e flores de boas-vindas para reserva de Mariana.',
    sector: 'Governanca',
    status: 'Concluido',
    priority: 'Media',
    roomNumber: '202',
    assignedTo: 'Maria Helena',
    createdAt: '2026-09-02T09:00:00Z',
    updatedAt: '2026-09-02T10:15:00Z'
  },

  // Cozinha / Restaurante
  {
    id: 'task_coz_1',
    title: 'Pedido Room Service: 2x Filé Poivre + 1x Sunset Drink',
    description: 'Destino: Quarto 201. Sem cebola no molho. Empratamento com cloche térmico.',
    sector: 'Cozinha',
    status: 'Em_Andamento',
    priority: 'Alta',
    roomNumber: '201',
    guestName: 'Dra. Fernanda Vasconcelos',
    assignedTo: 'Chef Rodrigo',
    relatedType: 'Cozinha',
    createdAt: '2026-09-02T19:10:00Z',
    updatedAt: '2026-09-02T19:15:00Z'
  },
  {
    id: 'task_coz_2',
    title: 'Preparação Café Imperial para Quarto 301 (Amanhã 08h30)',
    description: 'Separar frutas frescas, pães sem glúten e geleias artesanais para serviço matinal.',
    sector: 'Cozinha',
    status: 'A_Fazer',
    priority: 'Media',
    roomNumber: '301',
    guestName: 'Roberto Silveira Neto',
    assignedTo: 'Confeitaria / Cozinha',
    createdAt: '2026-09-02T16:00:00Z',
    updatedAt: '2026-09-02T16:00:00Z'
  },

  // Room Service
  {
    id: 'task_rs_1',
    title: 'Montagem de Bandeja e Entrega - Quarto 201',
    description: 'Acompanhar saída dos pratos da cozinha, talheres de prata e taça para drink.',
    sector: 'RoomService',
    status: 'A_Fazer',
    priority: 'Alta',
    roomNumber: '201',
    guestName: 'Dra. Fernanda Vasconcelos',
    assignedTo: 'Garçom Bruno',
    relatedType: 'Cozinha',
    createdAt: '2026-09-02T19:12:00Z',
    updatedAt: '2026-09-02T19:12:00Z'
  },
  {
    id: 'task_rs_2',
    title: 'Reposição Frigobar Especial - Suíte 301',
    description: 'Entregar 2x Espumante Chandon Brut e 2x Castanhas Nobres solicitados pelo hóspede.',
    sector: 'RoomService',
    status: 'Concluido',
    priority: 'Alta',
    roomNumber: '301',
    guestName: 'Roberto Silveira Neto',
    assignedTo: 'Atendente Tiago',
    relatedType: 'Frigobar',
    createdAt: '2026-09-02T15:30:00Z',
    updatedAt: '2026-09-02T15:45:00Z'
  },

  // Manutenção
  {
    id: 'task_man_1',
    title: 'Revisão Técnica no Ar Condicionado - Quarto 203',
    description: 'Verificar sensor de temperatura e carga de gás antes de liberar quarto no sistema.',
    sector: 'Manutencao',
    status: 'Em_Andamento',
    priority: 'Urgente',
    roomNumber: '203',
    assignedTo: 'Técnico Marcos',
    relatedType: 'Manutencao',
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-02T14:20:00Z'
  },
  {
    id: 'task_man_2',
    title: 'Ajuste de Vedação na Ducha do Quarto 102',
    description: 'Revisão preventiva no misturador monocomando de água quente.',
    sector: 'Manutencao',
    status: 'Concluido',
    priority: 'Baixa',
    roomNumber: '102',
    assignedTo: 'Técnico Marcos',
    createdAt: '2026-09-01T14:00:00Z',
    updatedAt: '2026-09-01T16:30:00Z'
  },

  // Recepção / Front Desk
  {
    id: 'task_rec_1',
    title: 'Preparar Check-in de Mariana Albuquerque (Reserva RES-84913)',
    description: 'Imprimir ficha de registro (FNRH) e programar cartão magnético para Quarto 202.',
    sector: 'Recepcao',
    status: 'A_Fazer',
    priority: 'Media',
    roomNumber: '202',
    guestName: 'Mariana Lima de Albuquerque',
    assignedTo: 'Recepcionista Camila',
    relatedType: 'Reserva',
    createdAt: '2026-09-02T18:00:00Z',
    updatedAt: '2026-09-02T18:00:00Z'
  },
  {
    id: 'task_rec_2',
    title: 'Auditoria Noturna e Fechamento de Lançamentos de Frigobar',
    description: 'Conferir lançamentos de consumo do dia e conciliação de cartões.',
    sector: 'Recepcao',
    status: 'A_Fazer',
    priority: 'Baixa',
    assignedTo: 'Auditor Noturno Rafael',
    createdAt: '2026-09-02T18:30:00Z',
    updatedAt: '2026-09-02T18:30:00Z'
  }
];

export const defaultTransactions: FinancialTransaction[] = [
  {
    id: 'tx_001',
    type: 'Receita',
    category: 'Diarias',
    description: 'Entrada 50% Diárias - Carlos Eduardo (Reserva RES-84910)',
    amount: 760,
    paymentMethod: 'Cartao_Credito',
    status: 'Pago',
    reservationId: 'res_001',
    roomNumber: '101',
    guestName: 'Carlos Eduardo Mendes',
    date: '2026-09-01',
    createdAt: '2026-09-01T14:20:00Z'
  },
  {
    id: 'tx_002',
    type: 'Receita',
    category: 'Diarias',
    description: 'Quitação Integral 4 Diárias - Dra. Fernanda (Reserva RES-84911)',
    amount: 2360,
    paymentMethod: 'PIX',
    status: 'Pago',
    reservationId: 'res_002',
    roomNumber: '201',
    guestName: 'Dra. Fernanda Vasconcelos',
    date: '2026-09-02',
    createdAt: '2026-09-02T13:55:00Z'
  },
  {
    id: 'tx_003',
    type: 'Receita',
    category: 'Diarias',
    description: 'Entrada 50% Diárias Suíte Presidencial - Roberto Silveira (RES-84912)',
    amount: 2375,
    paymentMethod: 'Cartao_Credito',
    status: 'Pago',
    reservationId: 'res_003',
    roomNumber: '301',
    guestName: 'Roberto Silveira Neto',
    date: '2026-09-02',
    createdAt: '2026-09-02T15:15:00Z'
  },
  {
    id: 'tx_004',
    type: 'Receita',
    category: 'Frigobar',
    description: 'Consumo Frigobar: 2x Espumante Chandon + 2x Castanhas - Quarto 301',
    amount: 174,
    paymentMethod: 'Faturado',
    status: 'Pendente',
    reservationId: 'res_003',
    roomNumber: '301',
    guestName: 'Roberto Silveira Neto',
    date: '2026-09-02',
    createdAt: '2026-09-02T15:45:00Z'
  },
  {
    id: 'tx_005',
    type: 'Receita',
    category: 'Cozinha',
    description: 'Room Service Restaurante: 2x Filé Poivre + 1x Sunset Drink - Quarto 201',
    amount: 230,
    paymentMethod: 'Faturado',
    status: 'Pendente',
    reservationId: 'res_002',
    roomNumber: '201',
    guestName: 'Dra. Fernanda Vasconcelos',
    date: '2026-09-02',
    createdAt: '2026-09-02T19:10:00Z'
  },
  {
    id: 'tx_006',
    type: 'Despesa',
    category: 'Operacional',
    description: 'Compra de Frutas e Laticínios Frescos para Restaurante',
    amount: 680,
    paymentMethod: 'PIX',
    status: 'Pago',
    date: '2026-09-02',
    createdAt: '2026-09-02T08:30:00Z'
  },
  {
    id: 'tx_007',
    type: 'Despesa',
    category: 'Manutencao',
    description: 'Peças e Filtros para Manutenção Preventiva Ar Condicionado',
    amount: 350,
    paymentMethod: 'PIX',
    status: 'Pago',
    date: '2026-09-01',
    createdAt: '2026-09-01T15:00:00Z'
  }
];

export const defaultInventoryItems: InventoryItem[] = [
  // Frigobar (Subestoque Quarto/Frigobar)
  {
    id: 'inv_mb_001',
    sku: 'FRIG-AGUA-500',
    name: 'Água Mineral sem Gás 500ml',
    sector: 'Frigobar',
    category: 'Bebidas',
    currentStock: 48,
    minStock: 25,
    maxStock: 120,
    unit: 'un',
    costPrice: 2.20,
    sellingPrice: 8.00,
    supplier: 'Distribuidora Cristal das Águas',
    locationBarcode: '78910001001',
    linkedMinibarItemId: 'mb_001',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_mb_002',
    sku: 'FRIG-CERV-CORONA',
    name: 'Cerveja Corona Extra 330ml',
    sector: 'Frigobar',
    category: 'Bebidas',
    currentStock: 32,
    minStock: 20,
    maxStock: 80,
    unit: 'un',
    costPrice: 6.50,
    sellingPrice: 18.00,
    supplier: 'Ambev Regional',
    locationBarcode: '78910001002',
    linkedMinibarItemId: 'mb_002',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_mb_003',
    sku: 'FRIG-VINHO-MALBEC',
    name: 'Vinho Tinto Malbec Reserva 375ml',
    sector: 'Frigobar',
    category: 'Vinhos',
    currentStock: 14,
    minStock: 10,
    maxStock: 30,
    unit: 'un',
    costPrice: 28.00,
    sellingPrice: 65.00,
    supplier: 'Adega Gran Sul Importados',
    locationBarcode: '78910001003',
    linkedMinibarItemId: 'mb_003',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_mb_004',
    sku: 'FRIG-CAST-CAJU',
    name: 'Castanhas de Caju Premium 100g',
    sector: 'Frigobar',
    category: 'Snacks',
    currentStock: 22,
    minStock: 15,
    maxStock: 50,
    unit: 'un',
    costPrice: 8.00,
    sellingPrice: 22.00,
    supplier: 'Nordeste Castanhas Gourmet',
    locationBarcode: '78910001004',
    linkedMinibarItemId: 'mb_004',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_mb_005',
    sku: 'FRIG-CHOC-70',
    name: 'Chocolate Artesanal 70% Cacau 80g',
    sector: 'Frigobar',
    category: 'Doces',
    currentStock: 8, // Critical alert!
    minStock: 15,
    maxStock: 40,
    unit: 'un',
    costPrice: 6.00,
    sellingPrice: 16.00,
    supplier: 'Chocolataria da Serra',
    locationBarcode: '78910001005',
    linkedMinibarItemId: 'mb_005',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_mb_006',
    sku: 'FRIG-COCA-LATA',
    name: 'Refrigerante Coca-Cola 350ml',
    sector: 'Frigobar',
    category: 'Bebidas',
    currentStock: 40,
    minStock: 20,
    maxStock: 100,
    unit: 'un',
    costPrice: 3.10,
    sellingPrice: 9.00,
    supplier: 'Coca-Cola FEMSA Distribuição',
    locationBarcode: '78910001006',
    linkedMinibarItemId: 'mb_006',
    updatedAt: '2026-09-02T10:00:00Z'
  },

  // Alimentos & Bebidas (Cozinha & Restaurante)
  {
    id: 'inv_ab_001',
    sku: 'AB-CAFE-GRAOS-KG',
    name: 'Café Especial em Grãos Arábica 100% 1kg',
    sector: 'Alimentos_Bebidas',
    category: 'Bebidas & Matérias-Primas',
    currentStock: 18,
    minStock: 10,
    maxStock: 40,
    unit: 'kg',
    costPrice: 48.00,
    sellingPrice: 0,
    supplier: 'Torrefação Mogiana Premium',
    locationBarcode: '78920002001',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_ab_002',
    sku: 'AB-FILE-MIGNON-KG',
    name: 'Filé Mignon Bovino Porcionado Limpo 1kg',
    sector: 'Alimentos_Bebidas',
    category: 'Carnes & Proteínas',
    currentStock: 6, // Low stock alert!
    minStock: 12,
    maxStock: 30,
    unit: 'kg',
    costPrice: 62.00,
    sellingPrice: 0,
    supplier: 'Frigorífico Premium Carnes Nobres',
    locationBarcode: '78920002002',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_ab_003',
    sku: 'AB-QUEIJO-BRIE-KG',
    name: 'Queijo Francês Brie Seleção Especial 1kg',
    sector: 'Alimentos_Bebidas',
    category: 'Laticínios',
    currentStock: 9,
    minStock: 5,
    maxStock: 20,
    unit: 'kg',
    costPrice: 75.00,
    sellingPrice: 0,
    supplier: 'Laticínios Serra Bella',
    locationBarcode: '78920002003',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_ab_004',
    sku: 'AB-CAMARAO-VG-KG',
    name: 'Camarão Rosa VG Descascado Congelado 1kg',
    sector: 'Alimentos_Bebidas',
    category: 'Pescados & Frutos do Mar',
    currentStock: 4, // Critical stock!
    minStock: 8,
    maxStock: 25,
    unit: 'kg',
    costPrice: 98.00,
    sellingPrice: 0,
    supplier: 'Pescados da Ilha Distribuidora',
    locationBarcode: '78920002004',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_ab_005',
    sku: 'AB-AZEITE-EV-500',
    name: 'Azeite de Oliva Extra Virgem 0.2% Acidez 500ml',
    sector: 'Alimentos_Bebidas',
    category: 'Mercearia Fina',
    currentStock: 24,
    minStock: 12,
    maxStock: 48,
    unit: 'un',
    costPrice: 38.00,
    sellingPrice: 0,
    supplier: 'Olivas do Sul Empório',
    locationBarcode: '78920002005',
    updatedAt: '2026-09-02T10:00:00Z'
  },

  // Governança & Enxoval (Housekeeping)
  {
    id: 'inv_gov_001',
    sku: 'GOV-AMEN-SHAMP-50',
    name: 'Kit Amenities Shampoo & Condicionador Alecrim 50ml',
    sector: 'Governanca_Enxoval',
    category: 'Amenities de Quarto',
    currentStock: 120,
    minStock: 60,
    maxStock: 300,
    unit: 'un',
    costPrice: 3.50,
    sellingPrice: 0,
    supplier: 'EcoSpa Cosméticos Naturais',
    locationBarcode: '78930003001',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_gov_002',
    sku: 'GOV-AMEN-SABON-BARRA',
    name: 'Sabonete Vegetal Karité e Algodão 40g',
    sector: 'Governanca_Enxoval',
    category: 'Amenities de Quarto',
    currentStock: 140,
    minStock: 80,
    maxStock: 400,
    unit: 'un',
    costPrice: 1.80,
    sellingPrice: 0,
    supplier: 'EcoSpa Cosméticos Naturais',
    locationBarcode: '78930003002',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_gov_003',
    sku: 'GOV-ENX-TOALHA-BANHO',
    name: 'Toalha de Banho 550g/m² Algodão Egípcio Branca',
    sector: 'Governanca_Enxoval',
    category: 'Enxoval & Rouparia',
    currentStock: 65,
    minStock: 40,
    maxStock: 120,
    unit: 'un',
    costPrice: 42.00,
    sellingPrice: 0,
    supplier: 'Têxtil Hotelaria Brasil',
    locationBarcode: '78930003003',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_gov_004',
    sku: 'GOV-ENX-LENCOL-KING',
    name: 'Jogo Lençol King Size 400 Fios Cetim Algodão',
    sector: 'Governanca_Enxoval',
    category: 'Enxoval & Rouparia',
    currentStock: 28,
    minStock: 20,
    maxStock: 60,
    unit: 'un',
    costPrice: 110.00,
    sellingPrice: 0,
    supplier: 'Têxtil Hotelaria Brasil',
    locationBarcode: '78930003004',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_gov_005',
    sku: 'GOV-LIMP-DESINF-5L',
    name: 'Desinfetante Hospitalar Concentrado Lavanda 5L',
    sector: 'Governanca_Enxoval',
    category: 'Produtos de Higienização',
    currentStock: 7, // Alert
    minStock: 10,
    maxStock: 25,
    unit: 'un',
    costPrice: 55.00,
    sellingPrice: 0,
    supplier: 'Química Limpeza Profissional',
    locationBarcode: '78930003005',
    updatedAt: '2026-09-02T10:00:00Z'
  },

  // Manutenção Predial & Técnica
  {
    id: 'inv_man_001',
    sku: 'MAN-LAMP-LED-9W',
    name: 'Lâmpada LED Dimerizável Branco Quente 9W E27',
    sector: 'Manutencao',
    category: 'Elétrica & Iluminação',
    currentStock: 34,
    minStock: 20,
    maxStock: 80,
    unit: 'un',
    costPrice: 14.50,
    sellingPrice: 0,
    supplier: 'Eletro Luz & Ferragens',
    locationBarcode: '78940004001',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_man_002',
    sku: 'MAN-PILHA-AAA-PCT',
    name: 'Pilhas Alcalinas AAA Cartela c/ 4un (Controles/Fechaduras)',
    sector: 'Manutencao',
    category: 'Elétrica & Automação',
    currentStock: 16,
    minStock: 12,
    maxStock: 50,
    unit: 'pct',
    costPrice: 18.00,
    sellingPrice: 0,
    supplier: 'Eletro Luz & Ferragens',
    locationBarcode: '78940004002',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_man_003',
    sku: 'MAN-FILTRO-AR-SPLIT',
    name: 'Filtro Antibacteriano Reposição Ar Condicionado Split',
    sector: 'Manutencao',
    category: 'Climatização & Refrigeração',
    currentStock: 5, // Critical!
    minStock: 10,
    maxStock: 25,
    unit: 'un',
    costPrice: 45.00,
    sellingPrice: 0,
    supplier: 'ClimaTech Refrigeração',
    locationBarcode: '78940004003',
    updatedAt: '2026-09-02T10:00:00Z'
  },

  // Almoxarifado Central (Depósito Principal)
  {
    id: 'inv_alm_001',
    sku: 'ALM-PAPEL-HIG-CX',
    name: 'Papel Higiênico Folha Tripla Caixa c/ 64 Rolos',
    sector: 'Almoxarifado',
    category: 'Consumíveis Gerais',
    currentStock: 14,
    minStock: 8,
    maxStock: 30,
    unit: 'cx',
    costPrice: 120.00,
    sellingPrice: 0,
    supplier: 'Papéis & Celulose Rio Verde',
    locationBarcode: '78950005001',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_alm_002',
    sku: 'ALM-FARDO-AGUA-CX',
    name: 'Fardo Água Mineral 500ml c/ 12 Unidades (Pulmão Central)',
    sector: 'Almoxarifado',
    category: 'Estoque Pulmão A&B',
    currentStock: 45,
    minStock: 25,
    maxStock: 100,
    unit: 'fardo',
    costPrice: 22.00,
    sellingPrice: 0,
    supplier: 'Distribuidora Cristal das Águas',
    locationBarcode: '78950005002',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'inv_alm_003',
    sku: 'ALM-TACA-CRISTAL-CX',
    name: 'Taças de Cristal Sommelier p/ Vinho Cx c/ 6un',
    sector: 'Almoxarifado',
    category: 'Utensílios & Enxoval',
    currentStock: 10,
    minStock: 6,
    maxStock: 25,
    unit: 'cx',
    costPrice: 165.00,
    sellingPrice: 0,
    supplier: 'Cristais Bohemia Brasil',
    locationBarcode: '78950005003',
    updatedAt: '2026-09-02T10:00:00Z'
  }
];

export const defaultStockMovements: StockMovement[] = [
  {
    id: 'mov_001',
    timestamp: '2026-09-02T08:30:00Z',
    itemId: 'inv_alm_002',
    itemName: 'Fardo Água Mineral 500ml c/ 12 Unidades (Pulmão Central)',
    sector: 'Almoxarifado',
    type: 'Entrada_Compra',
    quantity: 30,
    previousStock: 15,
    newStock: 45,
    unitCost: 22.00,
    totalCost: 660.00,
    originLocation: 'Distribuidora Cristal das Águas',
    destinationLocation: 'Almoxarifado Central - Pallet 03',
    operator: 'Carlos Silveira (Chefe de Suprimentos)',
    documentNumber: 'NF-e 88419',
    notes: 'Entrada de lote semanal com conferência física realizada sem avarias.'
  },
  {
    id: 'mov_002',
    timestamp: '2026-09-02T09:15:00Z',
    itemId: 'inv_mb_001',
    itemName: 'Água Mineral sem Gás 500ml',
    sector: 'Frigobar',
    type: 'Transferencia',
    quantity: 24,
    previousStock: 24,
    newStock: 48,
    unitCost: 2.20,
    totalCost: 52.80,
    originLocation: 'Almoxarifado Central',
    destinationLocation: 'Subestoque Frigobares - Andar 2 e 3',
    operator: 'Juliana Mendes (Supervisora de Governança)',
    documentNumber: 'TRANSF-0902-1',
    notes: 'Deslocamento de estoque pulmão para abastecimento dos carrinhos de frigobar.'
  },
  {
    id: 'mov_003',
    timestamp: '2026-09-02T14:30:00Z',
    itemId: 'inv_mb_002',
    itemName: 'Cerveja Corona Extra 330ml',
    sector: 'Frigobar',
    type: 'Saida_Consumo_Quarto',
    quantity: 2,
    previousStock: 34,
    newStock: 32,
    unitCost: 6.50,
    totalCost: 13.00,
    originLocation: 'Frigobar Quarto 301',
    destinationLocation: 'Consumo Hóspede',
    relatedRoomNumber: '301',
    relatedReservationId: 'res_003',
    operator: 'Marina Castro (Camareira / Governança)',
    notes: 'Consumo apurado na revisão da tarde e lançado na conta da Suíte Presidencial.'
  },
  {
    id: 'mov_004',
    timestamp: '2026-09-02T15:00:00Z',
    itemId: 'inv_gov_005',
    itemName: 'Desinfetante Hospitalar Concentrado Lavanda 5L',
    sector: 'Governanca_Enxoval',
    type: 'Saida_Uso_Interno',
    quantity: 1,
    previousStock: 8,
    newStock: 7,
    unitCost: 55.00,
    totalCost: 55.00,
    originLocation: 'DML Central',
    destinationLocation: 'Equipe de Higienização de Suítes',
    operator: 'Juliana Mendes (Supervisora de Governança)',
    notes: 'Abertura de galão para diluição e preparo dos pulverizadores da governança.'
  },
  {
    id: 'mov_005',
    timestamp: '2026-09-02T17:20:00Z',
    itemId: 'inv_ab_004',
    itemName: 'Camarão Rosa VG Descascado Congelado 1kg',
    sector: 'Alimentos_Bebidas',
    type: 'Saida_Venda_A_B',
    quantity: 2,
    previousStock: 6,
    newStock: 4,
    unitCost: 98.00,
    totalCost: 196.00,
    originLocation: 'Câmara Fria A&B',
    destinationLocation: 'Cozinha Principal - Ordem Room Service',
    relatedRoomNumber: '201',
    operator: 'Chef Rafael Albuquerque',
    documentNumber: 'ORD-ROOM-201',
    notes: 'Baixa para preparo de risoto de camarão especial servido no quarto.'
  }
];

export const defaultStaffUsers = [
  {
    id: 'usr_admin_001',
    email: 'alice@hotel.com',
    fullName: 'Alice Guimarães Teixeira',
    role: 'admin' as const,
    sector: 'Geral' as const,
    status: 'Ativo' as const,
    phone: '+55 (48) 99881-1001',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'view_overview' as const,
      'view_financial' as const,
      'manage_financial' as const,
      'view_rooms' as const,
      'manage_rooms' as const,
      'view_inventory' as const,
      'manage_inventory' as const,
      'view_kanbans' as const,
      'manage_all_kanbans' as const,
      'view_checkinout' as const,
      'manage_checkinout' as const,
      'view_guests' as const,
      'manage_guests' as const,
      'view_fnb' as const,
      'manage_fnb' as const,
      'manage_users' as const,
      'manage_settings' as const
    ],
    lastLoginAt: '2026-09-02T20:30:00Z',
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-09-02T12:00:00Z'
  },
  {
    id: 'usr_gerente_002',
    email: 'gerencia@hotel.com',
    fullName: 'Carlos Eduardo Silveira',
    role: 'gerente' as const,
    sector: 'Geral' as const,
    status: 'Ativo' as const,
    phone: '+55 (48) 99881-1002',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'view_overview' as const,
      'view_financial' as const,
      'view_rooms' as const,
      'manage_rooms' as const,
      'view_inventory' as const,
      'manage_inventory' as const,
      'view_kanbans' as const,
      'manage_all_kanbans' as const,
      'view_checkinout' as const,
      'manage_checkinout' as const,
      'view_guests' as const,
      'manage_guests' as const,
      'view_fnb' as const,
      'manage_fnb' as const,
      'manage_users' as const
    ],
    lastLoginAt: '2026-09-02T18:45:00Z',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-09-02T10:00:00Z'
  },
  {
    id: 'usr_recepcao_003',
    email: 'recepcao@hotel.com',
    fullName: 'Mariana Santos Rocha',
    role: 'recepcionista' as const,
    sector: 'Recepcao' as const,
    status: 'Ativo' as const,
    phone: '+55 (48) 99881-1003',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'view_rooms' as const,
      'view_checkinout' as const,
      'manage_checkinout' as const,
      'view_guests' as const,
      'manage_guests' as const,
      'view_kanbans' as const,
      'view_fnb' as const,
      'manage_fnb' as const
    ],
    lastLoginAt: '2026-09-02T19:10:00Z',
    createdAt: '2026-02-01T07:30:00Z',
    updatedAt: '2026-09-02T08:00:00Z'
  },
  {
    id: 'usr_governanca_004',
    email: 'governanca@hotel.com',
    fullName: 'Dona Neusa Aparecida',
    role: 'governanca' as const,
    sector: 'Governanca' as const,
    status: 'Ativo' as const,
    phone: '+55 (48) 99881-1004',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'view_rooms' as const,
      'manage_rooms' as const,
      'view_kanbans' as const,
      'view_fnb' as const,
      'manage_fnb' as const,
      'view_inventory' as const
    ],
    lastLoginAt: '2026-09-02T16:20:00Z',
    createdAt: '2026-02-10T06:00:00Z',
    updatedAt: '2026-09-01T15:00:00Z'
  },
  {
    id: 'usr_cozinha_005',
    email: 'cozinha@hotel.com',
    fullName: 'Chef Rodrigo Albuquerque',
    role: 'cozinha_roomservice' as const,
    sector: 'Cozinha' as const,
    status: 'Ativo' as const,
    phone: '+55 (48) 99881-1005',
    avatarUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'view_fnb' as const,
      'manage_fnb' as const,
      'view_kanbans' as const,
      'view_inventory' as const,
      'manage_inventory' as const
    ],
    lastLoginAt: '2026-09-02T20:05:00Z',
    createdAt: '2026-02-15T11:00:00Z',
    updatedAt: '2026-09-02T14:30:00Z'
  },
  {
    id: 'usr_manutencao_006',
    email: 'manutencao@hotel.com',
    fullName: 'Marcos Vinicius (Manutenção)',
    role: 'manutencao' as const,
    sector: 'Manutencao' as const,
    status: 'Ativo' as const,
    phone: '+55 (48) 99881-1006',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'view_rooms' as const,
      'manage_rooms' as const,
      'view_kanbans' as const,
      'view_inventory' as const,
      'manage_inventory' as const
    ],
    lastLoginAt: '2026-09-02T14:00:00Z',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-09-01T17:00:00Z'
  },
  {
    id: 'usr_financeiro_007',
    email: 'financeiro@hotel.com',
    fullName: 'Patrícia Faria Controller',
    role: 'financeiro' as const,
    sector: 'Financeiro' as const,
    status: 'Ativo' as const,
    phone: '+55 (48) 99881-1007',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    permissions: [
      'view_overview' as const,
      'view_financial' as const,
      'manage_financial' as const,
      'view_rooms' as const,
      'view_inventory' as const,
      'view_checkinout' as const,
      'view_guests' as const
    ],
    lastLoginAt: '2026-09-02T17:50:00Z',
    createdAt: '2026-03-10T09:30:00Z',
    updatedAt: '2026-09-02T16:00:00Z'
  }
];

